var countryNames = {
"AW": "Aruba",
"AF": "Afghanistan",
"AO": "Angola",
"AI": "Anguilla",
"AX": "Åland Islands",
"AL": "Albania",
"AD": "Andorra",
"AE": "United Arab Emirates",
"AR": "Argentina",
"AM": "Armenia",
"AS": "American Samoa",
"AQ": "Antarctica",
"TF": "French Southern Territories",
"AG": "Antigua and Barbuda",
"AU": "Australia",
"AT": "Austria",
"AZ": "Azerbaijan",
"BI": "Burundi",
"BE": "Belgium",
"BJ": "Benin",
"BQ": "Bonaire, Sint Eustatius and Saba",
"BF": "Burkina Faso",
"BD": "Bangladesh",
"BG": "Bulgaria",
"BH": "Bahrain",
"BS": "Bahamas",
"BA": "Bosnia and Herzegovina",
"BL": "Saint Barthélemy",
"BY": "Belarus",
"BZ": "Belize",
"BM": "Bermuda",
"BO": "Bolivia",
"BR": "Brazil",
"BB": "Barbados",
"BN": "Brunei Darussalam",
"BT": "Bhutan",
"BV": "Bouvet Island",
"BW": "Botswana",
"CF": "Central African Republic",
"CA": "Canada",
"CC": "Cocos (Keeling) Islands",
"CH": "Switzerland",
"CL": "Chile",
"CN": "China",
"CI": "Côte d'Ivoire",
"CM": "Cameroon",
"CD": "Congo, the Democratic Republic of the",
"CG": "Congo",
"CK": "Cook Islands",
"CO": "Colombia",
"KM": "Comoros",
"CV": "Cape Verde",
"CR": "Costa Rica",
"CU": "Cuba",
"CW": "Curaçao",
"CX": "Christmas Island",
"KY": "Cayman Islands",
"CY": "Cyprus",
"CZ": "Czech Republic",
"DE": "Germany",
"DJ": "Djibouti",
"DM": "Dominica",
"DK": "Denmark",
"DO": "Dominican Republic",
"DZ": "Algeria",
"EC": "Ecuador",
"EG": "Egypt",
"ER": "Eritrea",
"EH": "Western Sahara",
"ES": "Spain",
"EE": "Estonia",
"ET": "Ethiopia",
"FI": "Finland",
"FJ": "Fiji",
"FK": "Falkland Islands (Malvinas)",
"FR": "France",
"FO": "Faeroe Islands",
"FM": "Micronesia",
"GA": "Gabon",
"GB": "United Kingdom",
"GE": "Georgia",
"GG": "Guernsey",
"GH": "Ghana",
"GI": "Gibraltar",
"GN": "Guinea",
"GP": "Guadeloupe",
"GM": "Gambia",
"GW": "Guinea-Bissau",
"GQ": "Equatorial Guinea",
"GR": "Greece",
"GD": "Grenada",
"GL": "Greenland",
"GT": "Guatemala",
"GF": "French Guiana",
"GU": "Guam",
"GY": "Guyana",
"HK": "Hong Kong",
"HM": "Heard Island and McDonald Islands",
"HN": "Honduras",
"HR": "Croatia",
"HT": "Haiti",
"HU": "Hungary",
"ID": "Indonesia",
"IM": "Isle of Man",
"IN": "India",
"IO": "British Indian Ocean Territory",
"IE": "Ireland",
"IR": "Iran",
"IQ": "Iraq",
"IS": "Iceland",
"IL": "Israel",
"IT": "Italy",
"JM": "Jamaica",
"JE": "Jersey",
"JO": "Jordan",
"JP": "Japan",
"KZ": "Kazakhstan",
"KE": "Kenya",
"KG": "Kyrgyzstan",
"KH": "Cambodia",
"KI": "Kiribati",
"KN": "Saint Kitts and Nevis",
"KR": "South Korea",
"KW": "Kuwait",
"LA": "Laos",
"LB": "Lebanon",
"LR": "Liberia",
"LY": "Libya",
"LC": "Saint Lucia",
"LI": "Liechtenstein",
"LK": "Sri Lanka",
"LS": "Lesotho",
"LT": "Lithuania",
"LU": "Luxembourg",
"LV": "Latvia",
"MO": "Macao",
"MF": "Saint Martin (French part)",
"MA": "Morocco",
"MC": "Monaco",
"MD": "Moldova",
"MG": "Madagascar",
"MV": "Maldives",
"MX": "Mexico",
"MH": "Marshall Islands",
"MK": "Macedonia",
"ML": "Mali",
"MT": "Malta",
"MM": "Myanmar",
"ME": "Montenegro",
"MN": "Mongolia",
"MP": "Northern Mariana Islands",
"MZ": "Mozambique",
"MR": "Mauritania",
"MS": "Montserrat",
"MQ": "Martinique",
"MU": "Mauritius",
"MW": "Malawi",
"MY": "Malaysia",
"YT": "Mayotte",
"NA": "Namibia",
"NC": "New Caledonia",
"NE": "Niger",
"NF": "Norfolk Island",
"NG": "Nigeria",
"NI": "Nicaragua",
"NU": "Niue",
"NL": "Netherlands",
"NO": "Norway",
"NP": "Nepal",
"NR": "Nauru",
"NZ": "New Zealand",
"OM": "Oman",
"PK": "Pakistan",
"PA": "Panama",
"PN": "Pitcairn",
"PE": "Peru",
"PH": "Philippines",
"PW": "Palau",
"PG": "Papua New Guinea",
"PL": "Poland",
"PR": "Puerto Rico",
"KP": "North Korea",
"PT": "Portugal",
"PY": "Paraguay",
"PS": "Palestine",
"PF": "French Polynesia",
"QA": "Qatar",
"RE": "Réunion",
"RO": "Romania",
"RU": "Russian Federation",
"RW": "Rwanda",
"SA": "Saudi Arabia",
"SD": "Sudan",
"SN": "Senegal",
"SG": "Singapore",
"GS": "South Georgia and the South Sandwich Islands",
"SH": "Saint Helena ex. dep.",
"SJ": "Svalbard and Jan Mayen",
"SB": "Solomon Islands",
"SL": "Sierra Leone",
"SV": "El Salvador",
"SM": "San Marino",
"SO": "Somalia",
"PM": "Saint Pierre and Miquelon",
"RS": "Serbia",
"SS": "South Sudan",
"ST": "Sao Tome and Principe",
"SR": "Suriname",
"SK": "Slovakia",
"SI": "Slovenia",
"SE": "Sweden",
"SZ": "Swaziland",
"SX": "Sint Maarten (Dutch part)",
"SC": "Seychelles",
"SY": "Syria",
"TC": "Turks and Caicos Islands",
"TD": "Chad",
"TG": "Togo",
"TH": "Thailand",
"TJ": "Tajikistan",
"TK": "Tokelau",
"TM": "Turkmenistan",
"TL": "East Timor",
"TO": "Tonga",
"TT": "Trinidad and Tobago",
"TN": "Tunisia",
"TR": "Turkey",
"TV": "Tuvalu",
"TW": "Taiwan",
"TZ": "Tanzania, United Republic of",
"UG": "Uganda",
"UA": "Ukraine",
"UM": "United States Minor Outlying Islands",
"UY": "Uruguay",
"US": "United States of America",
"UZ": "Uzbekistan",
"VA": "Holy See (Vatican City State)",
"VC": "Saint Vincent and the Grenadines",
"VE": "Venezuela",
"VG": "British Virgin Islands",
"VI": "United States Virgin Islands",
"VN": "Viet Nam",
"VU": "Vanuatu",
"WF": "Wallis and Futuna Islands",
"WS": "Samoa",
"YE": "Yemen",
"ZA": "South Africa",
"ZM": "Zambia",
"ZW": "Zimbabwe"
}


var region = {
"Africa": [["Zimbabwe", "ZW"],
["Zambia", "ZM"],
["Western Sahara", "EH"],
["Uganda", "UG"],
["Tunisia", "TN"],
["South Africa", "ZA"],
["Somalia", "SO"],
["Sierra Leone", "SL"],
["Seychelles", "SC"],
["Senegal", "SN"],
["Sao Tome and Principe", "ST"],
["Saint Helena ex. dep.", "SH"],
["Rwanda", "RW"],
["Réunion", "RE"],
["Niger", "NE"],
["Namibia", "NA"],
["Mozambique", "MZ"],
["Morocco", "MA"],
["Mauritius", "MU"],
["Mauritania", "MR"],
["Malawi", "MW"],
["Madagascar", "MG"],
["Kenya", "KE"],
["Guinea", "GN"],
["Ghana", "GH"],
["Gambia", "GM"],
["Gabon", "GA"],
["Ethiopia", "ET"],
["Djibouti", "DJ"],
["Chad", "TD"],
["Cape Verde", "CV"],
["Cameroon", "CM"],
["Burundi", "BI"],
["Burkina Faso", "BF"],
["Botswana", "BW"],
["Benin", "BJ"],
["Angola", "AO"],
["Algeria", "DZ"]],
"Asia": [["Uzbekistan", "UZ"],
["Taiwan", "TW"],
["Tajikistan", "TJ"],
["South Korea", "KR"],
["Mongolia", "MN"],
["Kyrgyzstan", "KG"],
["Kazakhstan", "KZ"],
["Japan", "JP"],
["Georgia", "GE"],
["North Korea", "KP"],
["Macao", "MO"],
["Hong Kong", "HK"],
["China", "CN"],
["Azerbaijan", "AZ"],
["Armenia", "AM"]],
"Central America": [["Panama", "PA"],
["Nicaragua", "NI"],
["Honduras", "HN"],
["Guatemala", "GT"],
["El Salvador", "SV"],
["Costa Rica", "CR"],
["Belize", "BZ"]],
"Europe": [["United Kingdom", "GB"],
["Ukraine", "UA"],
["Macedonia", "MK"],
["Switzerland", "CH"],
["Sweden", "SE"],
["Spain", "ES"],
["Slovenia", "SI"],
["Slovakia", "SK"],
["Serbia", "RS"],
["San Marino", "SM"],
["Russian Federation", "RU"],
["Romania", "RO"],
["Moldova", "MD"],
["Portugal", "PT"],
["Poland", "PL"],
["Norway", "NO"],
["Netherlands", "NL"],
["Montenegro", "ME"],
["Monaco", "MC"],
["Malta", "MT"],
["Luxembourg", "LU"],
["Lithuania", "LT"],
["Liechtenstein", "LI"],
["Latvia", "LV"],
["Jersey", "JE"],
["Italy", "IT"],
["Isle of Man", "IM"],
["Ireland", "IE"],
["Iceland", "IS"],
["Hungary", "HU"],
["Holy See (Vatican City State)", "VA"],
["Guernsey", "GG"],
["Greece", "GR"],
["Gibraltar", "GI"],
["Germany", "DE"],
["France", "FR"],
["Finland", "FI"],
["Faeroe Islands", "FO"],
["Estonia", "EE"],
["Denmark", "DK"],
["Czech Republic", "CZ"],
["Croatia", "HR"],
["Bulgaria", "BG"],
["Belgium", "BE"],
["Belarus", "BY"],
["Austria", "AT"],
["Andorra", "AD"],
["Albania", "AL"],
["Åland Islands", "AX"]],
"Middle East": [["Yemen", "YE"],
["United Arab Emirates", "AE"],
["Turkey", "TR"],
["Syria", "SY"],
["Saudi Arabia", "SA"],
["Qatar", "QA"],
["Palestine", "PS"],
["Oman", "OM"],
["Lebanon", "LB"],
["Kuwait", "KW"],
["Jordan", "JO"],
["Israel", "IL"],
["Iran", "IR"],
["Egypt", "EG"],
["Cyprus", "CY"],
["Bahrain", "BH"]],
"North America": [["United States Virgin Islands", "VI"],
["United States of America", "US"],
["Turks and Caicos Islands", "TC"],
["Trinidad and Tobago", "TT"],
["Saint Pierre and Miquelon", "PM"],
["Saint Lucia", "LC"],
["Puerto Rico", "PR"],
["Mexico", "MX"],
["Martinique", "MQ"],
["Jamaica", "JM"],
["Haiti", "HT"],
["Guadeloupe", "GP"],
["Greenland", "GL"],
["Dominican Republic", "DO"],
["Cuba", "CU"],
["Cayman Islands", "KY"],
["Canada", "CA"],
["British Virgin Islands", "VG"],
["Bermuda", "BM"],
["Bahamas", "BS"],
["Aruba", "AW"],
["Anguilla", "AI"]],
"Oceania": [["Wallis and Futuna Islands", "WF"],
["Vanuatu", "VU"],
["Tuvalu", "TV"],
["Tonga", "TO"],
["Solomon Islands", "SB"],
["Samoa", "WS"],
["Pitcairn", "PN"],
["Papua New Guinea", "PG"],
["Palau", "PW"],
["Northern Mariana Islands", "MP"],
["Norfolk Island", "NF"],
["Niue", "NU"],
["New Zealand", "NZ"],
["New Caledonia", "NC"],
["Nauru", "NR"],
["Micronesia", "FM"],
["Marshall Islands", "MH"],
["Kiribati", "KI"],
["Guam", "GU"],
["French Polynesia", "PF"],
["Fiji", "FJ"],
["Cook Islands", "CK"],
["Australia", "AU"],
["American Samoa", "AS"]],
"South America": [["Venezuela", "VE"],
["Uruguay", "UY"],
["Suriname", "SR"],
["Peru", "PE"],
["Paraguay", "PY"],
["Guyana", "GY"],
["French Guiana", "GF"],
["Falkland Islands (Malvinas)", "FK"],
["Ecuador", "EC"],
["Colombia", "CO"],
["Chile", "CL"],
["Brazil", "BR"],
["Bolivia", "BO"],
["Argentina", "AR"]],
"South Asia": [["Sri Lanka", "LK"],
["Pakistan", "PK"],
["Nepal", "NP"],
["Maldives", "MV"],
["India", "IN"],
["Bhutan", "BT"],
["Bangladesh", "BD"],
["Afghanistan", "AF"]],
"Southeast Asia": [["Viet Nam", "VN"],
["Thailand", "TH"],
["Singapore", "SG"],
["Philippines", "PH"],
["Malaysia", "MY"],
["Laos", "LA"],
["Indonesia", "ID"],
["East Timor", "TL"],
["Cambodia", "KH"],
["Brunei Darussalam", "BN"]]
}
